---
- name: download systemd-swap and unarchive
  unarchive:
    src: https://github.com/Nefelim4ag/systemd-swap/archive/4.0.1.tar.gz
    dest: /usr/local/src
    remote_src: yes

- name: make & install systemd-swap
  shell: |
    make install
  args:
    chdir: /usr/local/src/systemd-swap-4.0.1
    executable: /bin/bash

- name: "Config systemd-swap"
  lineinfile:
    path: /etc/systemd/swap.conf
    regexp: '^swapfc_enabled=0'
    line: 'swapfc_enabled=1'

- name: enable and start service
  systemd:
    name: systemd-swap
    state: started
    enabled: yes
    daemon_reload: yes