---

- name: Install web server and PHP packages
  pacman:
    name: "{{ apache_packages }}"
    state: present
  register: apache_install

- name: Create nextcloud databases
  mysql_db:
    name: "{{ item.name }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_databases }}"
  register: db_creation

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host|default('localhost') }}"
    priv: "{{ item.priv }}"
    append_privs: "{{ item.append_privs|default('no') }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_users }}"
  when: db_creation is success

- name: download nextcloud and unarchive
  unarchive:
    src: https://download.nextcloud.com/server/releases/latest-15.tar.bz2
    dest: /var/www/html
    remote_src: yes
    owner: http
    group: http

- name: Creates data directory
  file:
    path: /var/www/html/nextcloud/data
    state: directory
    owner: http
    group: http

- name: "Config httpd"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen 8080'

- name: "Config httpd Virtual hosts"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: 'Include conf/vhosts/nextcloud.conf'

- name: "Config httpd PHP"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^LoadModule mpm_event_module modules/mod_mpm_event.so'
    line: '#LoadModule mpm_event_module modules/mod_mpm_event.so'

- name: "Config httpd PHP"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
    line: 'LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'

- name: "Config httpd PHP"
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '^#LoadModule rewrite_module modules/mod_rewrite.so'
    content: |
        LoadModule php7_module modules/libphp7.so
        AddHandler php7-script .php

- name: "Config httpd PHP"
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '^#Include conf/extra/httpd-ssl.conf'
    content: |
        Include conf/extra/php7_module.conf

- name: Config nextcloud httpd
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: "nextcloud.conf"
      dest: "/etc/httpd/conf/vhosts"
      mode: "0644"
  register: httpd_config_status

- name: Config PHP
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: "php.ini"
      dest: "/etc/php"
      mode: "0644"
  register: PHP_config_status

- name: enable and start service
  systemd:
    name: httpd
    state: started
    enabled: yes