---

- name: Install web server and PHP packages
  pacman:
    name: "{{ apache_packages }}"
    state: present
  register: apache_install

- name: Create nextcloud databases
  mysql_db:
    name: "{{ item.name }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_databases }}"
  register: db_creation

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host|default('localhost') }}"
    priv: "{{ item.priv }}"
    append_privs: "{{ item.append_privs|default('no') }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_users }}"
  when: db_creation is success

- name: Creates www directory
  file:
    path: /opt/www
    state: directory
    owner: http
    group: http

- name: download nextcloud and unarchive
  unarchive:
    src: https://download.nextcloud.com/server/releases/latest-15.tar.bz2
    dest: /opt/www
    remote_src: yes
    owner: http
    group: http

- name: Creates data directory
  file:
    path: /opt/www/nextcloud/data
    state: directory
    owner: http
    group: http

- name: Config nextcloud httpd
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: "httpd.conf"
      dest: "/etc/httpd/conf"
      mode: "0644"
    - src: "nextcloud.conf"
      dest: "/etc/httpd/conf/extra"
      mode: "0644"
  register: httpd_config_status

- name: Config PHP
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: "php.ini"
      dest: "/etc/php"
      mode: "0644"
  register: PHP_config_status

- name: enable and start service
  systemd:
    name: httpd
    state: started
    enabled: yes