---
- name: install mariadb-server packages
  pacman:
    name: mariadb
    state: present
  register: mariadb_install

- name: Check if mysql_install_db is already configured.
  stat: path=/var/lib/mysql/mysql
  register: mysql_install_db_result

- name: init mariadb
  shell: |
    mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    executable: /bin/bash
  when: not mysql_install_db_result.stat.exists

- name: enable and start service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  when: mariadb_install is success

# This command will fail when the root password was set previously
- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

# tasks for mysql_user and mysql_db
- name: Install PyMySQL as prerequisite for mysql Ansible module
  pacman:
    name: python-mysqlclient
    state: present

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: root_pwd_check.rc == 0

- name: Set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0

- name: Remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent

