---

- name: install base-devel packages
  pacman:
    name: base-devel
    state: present
  register: base_devel_install

- name: Creates data directory
  file:
    path: "/home/{{ user_name }}/qbittorrent-nox"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: copy PKGBUILD
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "PKGBUILD"
      dest: "/home/{{ user_name }}/qbittorrent-nox"
      mode: "0644"
  register: PKGBUILD_config_status

- name: makepkg
  shell: |
    makepkg --syncdeps --noconfirm --noprogressbar
  args:
    chdir: "/home/{{ user_name }}/qbittorrent-nox"
    executable: /bin/bash
  become: true
  become_user: "{{ user_name }}"

- name: install
  shell: |
    pacman -U --noconfirm --noprogressbar qbittorrent-nox*.pkg.tar.xz
  args:
    chdir: "/home/{{ user_name }}/qbittorrent-nox"
    executable: /bin/bash

- name: enable and start service
  systemd:
    name: "qbittorrent-nox@{{ user_name }}"
    state: started
    enabled: yes
  when: start_service
