---
- name: Set New Machine
  hosts: la

  roles:
    # - role: new_user
    - role: qbittorrent-nox
    # - role: bbr
    # - role: nextcloud
    # - role: sshd_config # The last step to modify sshd config
