---
- name: Set New Machine
  hosts: la

  roles:
    # - role: new_user
    # - role: disable_iptables_selinux
    # - role: qbittorrent-nox
    # - role: bbr
    # - role: nextcloud
    - role: systemd-swap
    # - role: sshd_config # The last step to modify sshd config
