---
- name: "Config archlinucn Repository"
  blockinfile:
    path: /etc/pacman.conf
    content: |
        [archlinuxcn]
        Server = https://cdn.repo.archlinuxcn.org/$arch

- name: upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: install base packages
  pacman:
    name: "{{ packages }}"
    state: present
  register: base_install